#!/usr/bin/env python

from flask.ext.script import Manager
from initializer import application

manager = Manager(application)

@manager.command
def run():
    application.run(host='0.0.0.0', port=5000, debug=True)

if __name__ == '__main__':
    manager.run()
